pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'javac multi-stage-multi-agent/HelloWorld.java'
        sh 'java multi-stage-multi-agent/HelloWorld.java'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node multi-stage-multi-agent/hello.js'
      }
    }
  }
}
